server:
  listen: "0.0.0.0:8080"
log_level: debug

remotes:
  - name: 114
    uris:
      - udp://114.114.114.114:53
  - name: google
    uris:
      - doh://8.8.8.8?sni=dns.google
      - doh://8.8.4.4?sni=dns.google

rules:
  - DOMAIN-SUFFIX, google.com, google || ipv6=disable
  - DOMAIN-KEYWORD, bing, google || ipv6=only
  - DOMAIN, baidu.com, 114 || ipv6=prefer
  - GEOSITE, NETFLIX, google || ipv6=prefer
  - GEOSITE, CN, 114 || ipset4=cn4&ipset6=cn6
  - MATCH, google